### PR TITLE
allow users to pass their own loki config

### PR DESCRIPTION
**Pull request by attachmentgenie**

### CODE REVIEW

**Review by DerekStrickland — COMMENTED** [review]
This looks good as is, but I noticed that this requires docker volumes to be enabled. We ran into an issue with another pack running in a mixed cluster where some nodes had docker volumes enabled and some didn't.  Do you have time to update this with a constraint for that?

If not, no worries, I can approve as is, but it would be a nice addition.

**Comment by attachmentgenie** [comment]
@DerekStrickland do you have an example of the constraint you mentioned? i am looking through the other packs and i can only see 1 other pattern e.g.

https://github.com/hashicorp/nomad-pack-community-registry/blob/main/packs/promtail/templates/_helpers.tpl#L19-L29

**Comment by DerekStrickland** [comment]
For sure.  [Here's an example](https://github.com/hashicorp/nomad-pack-community-registry/blob/a090c22a9bf2ff667c5989890cf0b8332209ccb4/packs/fabio/templates/fabio.nomad.tpl#L8) of allowing users to add custom constraints.

And [here is the documentation](https://www.nomadproject.io/docs/job-specification/constraint) on constraints in general.

If you want to just hard code the one constraint, I think it would look like this.

```hcl
constraint {
    attribute = "${attr.driver.docker.volumes.enabled}"
    value     = "true"
  }
```

**Review by DerekStrickland — APPROVED** [review]
Nice addition!  Thanks!

**Pull request merged**
