### PR TITLE
switching to docker based chown task

### PR DESCRIPTION
**Pull request by attachmentgenie**
as discussed in #79

### CODE REVIEW

**Comment by efbar** [comment]
Good call @attachmentgenie!
Just a question, wouldn't be better to set busybox version to something not "latest"?

**Comment by attachmentgenie** [comment]
@efbar also a very good call, do you propose to hardcode what latest corresponds to now, or make it completely variable (feel a little over the top for just chown)

**Comment by efbar** [comment]
You're right regarding the overkill for just chown. What about "stable"? I think could be enough

**Comment by attachmentgenie** [comment]
a fare more sensible default, update pushed

**Pull request merged**
